export const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_USER_ROLE : 'SET_USER_ROLE',
    SET_PATIENT_ID: 'SET_PATIENT_ID',
    SET_MESSAGE_ID:"SET_MESSAGE_ID",
    SET_FETCH_ID:"SET_FETCH_ID"
  };