export const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_USER_ROLE : 'SET_USER_ROLE',
    SET_USER_IMAGE : 'SET_USER_IMAGE',
    SET_PATIENT_ID: 'SET_PATIENT_ID',
    SET_CONTACT_ARRAY:"SET_CONTACT_ARRAY",
    SET_CONTACT_TITLE:"SET_CONTACT_TITLE",
    SET_FETCH_ID:"SET_FETCH_ID",
    SET_DOCTOR_ID:'SET_DOCTOR_ID',
    SET_CHAT_ARRAY:"SET_CHAT_ARRAY",
    SET_TEXT_OBJECT:"SET_TEXT_OBJECT"
  };