# Generated by Django 3.1.4 on 2020-12-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
